
### **Desafio 1** - Lendo dados com vários parâmetros

Chegou a hora de você testar os conhecimentos desenvolvidos durante a aula. Temos um [arquivo CSV](https://raw.githubusercontent.com/alura-cursos/Pandas/main/dados_sus.csv), que foi obtido na página Informações de Saúde (TABNET) - DATASUS [texto do link](https://datasus.saude.gov.br/informacoes-de-saude-tabnet/). Este arquivo contém os gastos hospitalares públicos de cada uma das Unidades da Federação brasileira no período de janeiro de 2008 a março de 2021.

Seu desafio aqui será fazer a leitura desse arquivo utilizando a função `read_csv` da biblioteca Pandas. Alguns parâmetros devem ser adicionados para que a leitura seja feita corretamente. Então, seguem algumas dicas:

* Verifique se o arquivo CSV está separado por vírgula ou ponto e vírgula.
* A codificação do arquivo é ISO-8859-1.
* As três primeiras linhas linhas do arquivo podem ser desconsideradas, pois o cabeçalho só começa na quarta linha.
* As 9 últimas linhas também podem ser desconsideradas, pois são apenas informações sobre onde os dados foram obtidos.

In [ ]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/dados_sus.csv'

In [ ]:
dados_sus = pd.read_csv(url, encoding='ISO-8859-1', sep=';', skiprows=3, skipfooter=9, engine='python')

`engine='python'`: o motor usado para ler o arquivo é o Python. Isso é necessário quando se usa o parâmetro skipfooter, pois o motor padrão não suporta essa opção.

In [ ]:
dados_sus

Unidade da Federação      2008/Jan      2008/Fev      2008/Mar  \
0              Rondônia    1388528,39    2931283,42    1541682,52   
1                  Acre     902416,00    1497206,26    1794028,48   
2              Amazonas    4735529,42    7118990,57    8196635,49   
3               Roraima     657889,53     777939,31     718688,03   
4                  Pará   18864744,11   19553758,20   21937342,70   
5                 Amapá    1120973,34    1268740,33     974651,24   
6             Tocantins    3441592,69    4985688,85    6205612,60   
7              Maranhão   10723506,39   13559679,41   13985142,36   
8                 Piauí    7985142,43   10079928,25   10298372,45   
9                 Ceará   15539821,90   25735101,55   28724625,75   
10  Rio Grande do Norte    5947814,08    9509755,83   10352238,59   
11              Paraíba   10723002,45   11386274,47   12053643,87   
12           Pernambuco   14393949,89   24181400,95   29991302,71   
13              Alagoas    6243726,32    8376622,16    8408336,22   
14              Sergipe    2780750,11    3676483,16    5051473,61   
15                Bahia   21211522,47   28189304,95   34181483,52   
16         Minas Gerais   45671659,76   70194037,10   79231336,95   
17       Espírito Santo    5456723,98    9102212,86   10249595,97   
18       Rio de Janeiro   23025258,52   28394310,93   44567062,94   
19            São Paulo   91678473,48  148677526,82  156087269,23   
20               Paraná   38266347,46   55384670,52   53801318,85   
21       Santa Catarina   16504913,45   25651429,11   26743524,89   
22    Rio Grande do Sul   30931325,46   57363420,01   51547794,07   
23   Mato Grosso do Sul    5377392,11    7002472,61    8423933,19   
24          Mato Grosso    4795299,01    8684882,23    7886243,14   
25                Goiás   15310637,29   22258668,68   21442515,75   
26     Distrito Federal    4745919,19    7632480,67    9647203,26   
27                Total  408424859,23  613174269,21  664043058,38   

        2008/Abr      2008/Mai      2008/Jun      2008/Jul      2008/Ago  \
0     1525314,96    1645953,84    1406150,68    3065279,01    3231494,61   
1     1730469,42    1819443,92    1828496,00    2511754,59    2089107,14   
2     8259378,42    7831399,90    8477273,62    9368858,72    9352532,70   
3      839994,39     862347,96     832440,66     996693,09     894271,18   
4    20842829,69   23249952,88   23240687,56   24002223,56   23341218,03   
5     1141137,32     866346,18    1440978,95    1426659,48    1475551,38   
6     4984482,09    5511002,46    4927934,22    5445602,28    5413710,38   
7    14809416,46   14505727,38   14908091,32   15784899,40   15195312,89   
8    10775976,33   10398360,88   10528253,88   11040107,92   10549176,40   
9    30676457,06   30604453,47   31272395,18   30925391,36   27851438,72   
10   10855108,50   11160168,19   10475071,38   11386349,96   10640817,47   
11   12653528,76   12215107,11   12256928,49   12755413,77   12872578,37   
12   34806197,97   32147987,35   32239094,89   32685640,76   35457038,66   
13    9090794,82    9338771,45   10068210,08    9887061,61    9373432,00   
14    5046063,36    4741151,56    5401259,63    5521904,44    5238398,50   
15   39026934,13   42949566,82   47025972,04   47481695,17   46931248,28   
16   77136537,58   80554440,63   94758522,83   85360064,11   84722528,10   
17   11253833,56   10198619,17   13364258,29   13035374,08   12588595,77   
18   44054604,82   44911021,15   48056212,24   49872379,35   50912706,60   
19  161227125,43  187119397,64  187291126,07  194398399,48  184854516,35   
20   52460306,69   54419620,71   57811688,48   58094241,83   56982774,90   
21   27181488,26   26845308,18   29909762,04   30789135,84   31250854,33   
22   56673338,49   48397733,07   52413429,62   56636376,98   56113054,70   
23    8797487,68    9770421,80   10905392,18   10249299,82    9671553,45   
24    8794109,79    9231645,40   10221763,77    9163314,28    9243148,81   
25   20921212,45   216159

---
---
### **Desafio 2** - Lendo dados de outro link

Neste desafio, a sua função é efetuar a leitura do arquivo pelo link do Google Planilhas e depois salvar o DataFrame obtido no formato CSV. Link da planilha:
https://docs.google.com/spreadsheets/d/1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw/edit#gid=1214654498

In [ ]:
# Adicionando os parâmetros na url:
url = 'https://docs.google.com/spreadsheets/d/1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw/gviz/tq?tqx=out:csv&sheet'

In [ ]:
dados_sheets = pd.read_csv(url)
dados_sheets

Country Name country_code                      Region  \
0           Aruba          ABW   Latin America & Caribbean   
1     Afghanistan          AFG                  South Asia   
2          Angola          AGO          Sub-Saharan Africa   
3         Albania          ALB       Europe & Central Asia   
4         Andorra          AND       Europe & Central Asia   
..            ...          ...                         ...   
210         Samoa          WSM         East Asia & Pacific   
211   Yemen, Rep.          YEM  Middle East & North Africa   
212  South Africa          ZAF          Sub-Saharan Africa   
213        Zambia          ZMB          Sub-Saharan Africa   
214      Zimbabwe          ZWE          Sub-Saharan Africa   

                             Indicator Name           1990           1991  \
0    CO2 emissions (metric tons per capita)            NaN            NaN   
1    CO2 emissions (metric tons per capita)    191.745.115    167.681.579   
2    CO2 emissions (metric tons per capita)    553.661.955    544.538.649   
3    CO2 emissions (metric tons per capita)  1.819.541.634    124.281.022   
4    CO2 emissions (metric tons per capita)  7.521.831.658    723.537.924   
..                                      ...            ...            ...   
210  CO2 emissions (metric tons per capita)     55.283.574    609.756.098   
211  CO2 emissions (metric tons per capita)     56.703.735    690.937.429   
212  CO2 emissions (metric tons per capita)  6.729.798.587  6.424.621.766   
213  CO2 emissions (metric tons per capita)    340.929.635    349.232.211   
214  CO2 emissions (metric tons per capita)  1.585.443.976  1.713.321.439   

              1992           1993           1994           1995  ...  \
0              NaN            NaN            NaN            NaN  ...   
1       95.957.742      8.472.111     75.545.827     68.467.956  ...   
2      543.557.223     70.898.423    836.804.405    912.141.485  ...   
3      683.699.826    638.307.036    645.355.189    605.436.253  ...   
4       69.630.787  6.724.177.518  6.541.578.914  6.733.479.486  ...   
..             ...            ...            ...            ...  ...   
210    604.266.119    658.221.486    592.806.881    705.674.802  ...   
211    704.793.064    627.104.927    653.255.714    706.080.534  ...   
212  6.175.429.944  6.219.193.872  6.215.847.077  6.378.789.568  ...   
213     33.722.439    289.956.061    241.269.619    234.153.214  ...   
214  1.694.415.977  1.539.740.958  1.417.186.242    135.661.892  ...   

              2011           2012           2013           2014  \
0              NaN            NaN            NaN            NaN   
1       29.650.624    259.295.334     18.562.366    146.235.617   
2      985.522.312    950.695.879  1.036.293.852  1.099.779.111   
3      166.942.319    150.324.046  1.533.630.039  1.668.337.371   
4    5.850.886.105  5.944.654.173  5.942.800.412  5.807.127.723   
..             ...            ...            ...            ...   
210  1.066.843.067  1.057.703.002  1.048.701.723  1.092.498.145   
211    963.978.488    858.490.955  1.106.687.715  1.062.211.282   
212  7.869.815.906  8.077.957.969  8.138.264.312  8.212.241.156   
213    217.496.732     27.860.069    284.057.568    304.549.552   
214     88.488.553    915.734.944    919.824.123    889.104.126   

              2015           2016           2017           2018  \
0              NaN            NaN            NaN            NaN   
1      172.896.741    149.789.334    131.694.556      1.632.953   
2      113.504.405  1.031.811.348     81.330.073    777.674.934   
3      160.377.515  1.557.664.358  1.788.786.074  1.782.738.948   
4    6.026.181.822  6.080.600.282  6.104.133.912  6.362.975.399   
..             ...            ...            ...            ...   
210  1.240.245.954  1.542.099.372  1.586.830.344  1.478.626.161   
211    511.361.652    399.363.829    359.621.635    341.068.402   
212  7.669.937.662  7.563.739.495  7.641.675.086  7.515.678.60

In [ ]:
dados_sheets.to_csv('dados_co2.csv')

---
### **Desafio 3** -  Lendo uma tabela de uma página web

Chegou a hora de testar os conhecimentos desenvolvidos durante a aula.

Vanessa é uma cientista de dados que está realizando algumas análises com dados ambientais. Ela está desenvolvendo um projeto para avaliar o impacto ambiental das atividades humanas em diferentes países do mundo, mas para isso precisa das estimativas populacionais desses países. Ao pesquisar na internet, encontrou uma tabela de estimativas populacionais em um artigo da página [Wikipédia](https://https://pt.wikipedia.org/wiki/Lista_de_pa%C3%ADses_por_popula%C3%A7%C3%A3o).

Assim como Vanessa, seu desafio é obter um DataFrame da tabela que contém as informações do número de habitantes de cada país.

In [ ]:
populacao_paises = pd.read_html('https://pt.wikipedia.org/wiki/Lista_de_pa%C3%ADses_por_popula%C3%A7%C3%A3o')[0]
populacao_paises

Unnamed: 0 Posição    País (ou território dependente) Estimativa da ONU  \
0           NaN       1                              Índia     1 429 921 746   
1           NaN       2                              China     1 426 391 281   
2           NaN       3                     Estados Unidos       339 987 103   
3           NaN       4                          Indonésia       277 184 719   
4           NaN       5                          Paquistão       240 215 932   
..          ...     ...                                ...               ...   
245         NaN       –     Ilha de Ascensão (Reino Unido)               806   
246         NaN     195                           Vaticano               801   
247         NaN       –  Ilhas Cocos (Keeling) (Austrália)               573   
248         NaN       –     Tristão da Cunha (Reino Unido)               241   
249         NaN       –       Ilhas Pitcairn (Reino Unido)                40   

     Data      Estimativa Oficial  
0    2023      Estimativa oficial  
1    2023           Censo oficial  
2    2023           Censo oficial  
3    2023      Estimativa oficial  
4    2023      Estimativa oficial  
..    ...                     ...  
245  2021  Estimativa oficial[10]  
246  2020      Estimativa oficial  
247  2020      Estimativa oficial  
248  2022  Estimativa oficial[11]  
249  2021      Estimativa oficial  

[250 rows x 6 columns]

---
### **Desafio 3** - manipulando um banco de dados

Chegou a hora de testar os conhecimentos desenvolvidos durante a aula.

Você é responsável por criar um banco de dados local de clientes para uma instituição financeira. Temos o [arquivo CSV](https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv) com os dados de clientes.

Sua missão é:

- Criar o banco de dados local com a biblioteca SQLAlchemy.
- Escrever os dados do arquivo CSV neste banco de dados local.
- Realizar três atualizações no banco de dados:
  1. Atualizar o registro do cliente de ID 6840104 que teve o rendimento anual alterado para 300000.
  2. Excluir o registro do cliente de ID 5008809, pois essa pessoa não possui mais conta na instituição financeira.
  3. Criar um novo registro de cliente seguindo as seguintes especificações: `ID_Cliente: 6850985; Idade: 33; Grau_escolaridade: Doutorado; Estado_civil: Solteiro; Tamanho_familia: 1; Categoria_de_renda: Empregado; Ocupacao: TI; Anos_empregado: 2; Rendimento_anual: 290000; Tem_carro: 0; Moradia: Casa/apartamento próprio`

> Dica importante: Para adicionar um(a) novo(a) cliente à tabela, utilize a cláusula INSERT INTO seguida do nome da tabela e depois especifique entre parênteses os nomes das colunas da tabela. Utilize a cláusula VALUES e, em seguida, passe entre parênteses os novos valores para esse novo registro. Certifique-se de que os valores estejam na ordem correta e no formato adequado para cada coluna.


In [ ]:
import pandas as pd
from sqlalchemy import create_engine, MetaData, Table, inspect

In [ ]:
engine = create_engine('sqlite:///:memory:')

In [ ]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'

In [ ]:
dados = pd.read_csv(url)

In [ ]:
dados

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008809     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840104     62      Ensino médio     Divorciado                1   
438459     6840222     43      Ensino médio       Solteiro                1   
438460     6841878     22   Ensino superior       Solteiro                1   
438461     6842765     59      Ensino médio         Casado                2   
438462     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458          Pensionista             Outro               0   
438459            Empregado  Construção Civil               8   
438460  Associado comercial            Vendas               1   
438461          Pensionista             Outro               0   
438462            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          135000.0          0  Casa/apartamento próprio  
438459          103500.0          0  Casa/apartamento próprio  
438460           54000.0          0          Mora com os pais  
438461           72000.0          0  Casa/apartamento próprio  
438462          121500.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]

In [ ]:
dados.to_sql('clientes', engine, index=False)

438463

In [ ]:
inspector = inspect(engine)
print(inspector.get_table_names())

['clientes']


1) Atualizando o rendimento anual do cliente de ID 6840104 para 300000.

In [ ]:
query = "UPDATE clientes SET Rendimento_anual=300000 WHERE ID_Cliente=6840104"
with engine.connect() as conn:
  conn.execute(query)

In [ ]:
query = "SELECT * FROM clientes WHERE ID_Cliente=6840104"
pd.read_sql(query, engine)

ID_Cliente  Idade Grau_escolaridade Estado_civil  Tamanho_familia  \
0     6840104     62      Ensino médio   Divorciado                1   

  Categoria_de_renda Ocupacao  Anos_empregado  Rendimento_anual  Tem_carro  \
0        Pensionista    Outro               0          300000.0          0   

                    Moradia  
0  Casa/apartamento próprio

2) Excluindo o registro do cliente de ID 5008809.

In [ ]:
query = "DELETE FROM clientes WHERE ID_Cliente=5008809"
with engine.connect() as conn:
  conn.execute(query)

In [ ]:
query = "SELECT * FROM clientes WHERE ID_Cliente=5008809"
pd.read_sql(query, engine)

Empty DataFrame
Columns: [ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia]
Index: []

3) Criando novo registro de cliente.

`ID_Cliente: 6850985; Idade: 33; Grau_escolaridade: Doutorado; Estado_civil: Solteiro; Tamanho_familia: 1; Categoria_de_renda: Empregado; Ocupacao: TI; Anos_empregado: 2; Rendimento_anual: 290000; Tem_carro: 0; Moradia: Casa/apartamento próprio`

In [ ]:
query = 'INSERT INTO clientes (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, '\
        'Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia) '\
        'VALUES (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", 2, 290000, 0, '\
        '"Casa/apartamento próprio")'

with engine.connect() as conn:
    conn.execute(query)

In [ ]:
query = "SELECT * FROM clientes WHERE ID_Cliente=6850985"
pd.read_sql(query, engine)

ID_Cliente  Idade Grau_escolaridade Estado_civil  Tamanho_familia  \
0     6850985     33         Doutorado     Solteiro                1   

  Categoria_de_renda Ocupacao  Anos_empregado  Rendimento_anual  Tem_carro  \
0          Empregado       TI               2          290000.0          0   

                    Moradia  
0  Casa/apartamento próprio